media:
  input: public
  output: /
content:
    - name: home
      label: Home page
      type: file
      path: src/pages/index.md
      fields:
        -
          name: layout
          type: string
          hidden: true
          default: "../layouts/Layout.astro"
        -
          name: title
          label: Title
          type: string
        -
          name: body
          label: Body
          type: rich-text
    - name: impress
      label: Impressum
      type: file
      path: src/pages/impressum.md
      fields:
        -
          name: layout
          type: string
          hidden: true
          default: "../layouts/Layout.astro"
        -
          name: title
          label: Title
          type: string
        -
          name: body
          label: Body
          type: rich-text
